/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 avatar.gltf --transform
Author: UARRR (https://sketchfab.com/UARRR)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/avatar-00eacfdef34b445683086f5c4abc8922
Title: Avatar
*/
import { useGLTF } from "@react-three/drei";

export function Avatar(props: any) {
  const { nodes, materials }: any = useGLTF("/avatar-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={5.3}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.Material}
            position={[0.13, 0.19, -0.81]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.Material}
            position={[0.13, 0.19, -0.81]}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials.Material}
            position={[0.02, -0.12, -0.42]}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials.Material}
            position={[0.02, -0.08, -0.42]}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials.Material}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials.Material}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/avatar-transformed.glb");
